### ISSUE TITLE
[2023OSS_Team Project_22조] 1. Mini project 설계

### ISSUE THREAD

**Issue by gue02** [osslab22/oss_team_lab#1]
1. 설계
주제 : 가계부 프로그램
Image(가계부)
프로젝트 구현 기능 설명
CRUD 기능, 데이터 파일 저장/읽어오기, 검색 메뉴 , 총액 계산 프로그램, 월 평균 계산
C 언어
팀 소개
한규영, 한은택

**Comment by gue02** [comment]
//CRUD 내용
int ceateLog(Product *p); // 가계부에 내용을 추가하는 함수
void readLog(Product *p); // 가계부의 내용 출력 함수
int updateLog(Product *p); // 가계부 내용을 수정하는 함수
int deleteLog(Product *p); // 가계부 내용을 삭제하는 함수
void saveLog(Product *p, int count); // 가계부의 내용을 저장하는 함수
int loadLog(Product *p);// 저장된 내용을 불러오는 함수
//추가 함수와 기능들
int Menu(); // 메뉴를 불러오고 리턴을 가져오는 함수
void searchLog(Product *p, int count); // 가계부의 내용을 검색하여 출력하는 함수
int totalLog(Product *p); // 가계부의 적힌 총액을 계산하는 함수
int averMonth(Product *p, int day); // 월 평균을 계산하는 함수

**Comment by gue02** [comment]
//역할분담
Repo 소유자 : 한규영 Contributor: 한은택
CRUD 함수 구현 내용

**Comment by Het0512** [comment]
Create - 가계부에 내용을 추가하는 함수
Read - 가계부 내용을 출력하는 함수
Update - 가계부 내용을 수정하는 함수
Delete - 가계부 내용을 삭제하는 함수
Load - 파일에 저장된 가계부 내용을 읽어오는 함수
Save - 가계부 내용을 파일에 저장하는 함수
Menu - 메뉴를 불러오는 함수
Search - 가계부의 내용을 검색하여 상세 정보를 출력하는 함수
Total - 가계부의 적힌 내용을 기반으로 현재 총 금액을 출력하는 함수
TotalMonth - 가계부의 적힌 내용을 기반으로 월마다 총 소비액을 출력하는 함수

**Comment by gue02** [comment]
//CRUD 내용
int ceateLog(Product *p); // 가계부에 내용을 추가하는 함수
void readLog(Product *p); // 가계부의 내용 출력 함수
int updateLog(Product *p); // 가계부 내용을 수정하는 함수
int deleteLog(Product *p); // 가계부 내용을 삭제하는 함수
void saveLog(Product *p, int count); // 가계부의 내용을 저장하는 함수
int loadLog(Product *p);// 저장된 내용을 불러오는 함수
//추가 함수와 기능들
int Menu(); // 메뉴를 불러오고 리턴을 가져오는 함수
void searchLog(Product *p, int count); // 가계부의 내용을 검색하여 출력하는 함수
int totalLog(Product *p); // 가계부의 적힌 총액을 계산하는 함수
int TotalMonth(Product *p, int month); // 가계부의 적힌 내용을 기반으로 월마다 총 소비액을 출력하는 함수
